url: https://pastelprospects.github.io
baseurl: ""

# Site settings
title: Pastel Prospects
email: support@pastelprospects.com
description: "Purposefully designing a more equitable and sustainable future alongside exceptional founders"


# Team names, titles and social links
people:
- name: Samuel Ekanem
  pic: 1
  position: Founder, Principal
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/samuel-ekanem/
    - title: medium
      url: https://medium.com/@samuelekanem
    - title: twitter
      url: https://twitter.com/sammypastel


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/company/pastel-venture-studio/about/
  - title: instagram
    url: https://instagram.com/pastel.plug
  - title: github
    url: https://github.com/pastelprospects


# Postal address (add as many lines as necessary)
address:
  - line: Oakland, CA 94612

# Build settings
markdown: kramdown
permalink: pretty